apiVersion: "v1"
kind: Pod
metadata:
  name: ofm-fe
  labels:
    name: ofm-frontend
    module: frontend
    environment: staging
spec:
  containers:
    - name: ofm-fe
      image: prch12/alpineweb:web1
      ports:
        - containerPort: 3000
          protocol: TCP
