apiVersion: v1
kind: Service
metadata:
  name: ofm-fe
  labels:
    name: ofm-frontend
    module: frontend
    environment: staging
spec:
  selector:
    name: ofm-fe
    module: frontend
    environment: staging

  type: NodePort
  ports:
   - port: 3000
     name: http
     targetPort: 3000
     protocol: TCP
     nodePort: 32500
